// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.FPMS_DB;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(FPMSDbContext))]
    [Migration("20251229230252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Shared.FPMS_DB.Entities.BatchStatus", b =>
                {
                    b.Property<int>("BatchStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchStatusName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("BatchStatusId");

                    b.ToTable("BatchStatus");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.Dispenser", b =>
                {
                    b.Property<int>("DispenserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiEndPoint")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("DispenserId");

                    b.ToTable("Dispenser");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.DispenserActionLog", b =>
                {
                    b.Property<int>("DispenserActionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiRequest")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiResponse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("DispenserActionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DispenserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsErrorOccured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("DispenserActionLogId");

                    b.ToTable("DispenserActionLog");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.DispenserActionType", b =>
                {
                    b.Property<int>("DispenserActionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DispenserActionTypeName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("DispenserActionTypeId");

                    b.ToTable("DispenserActionType");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.DispenserNozzle", b =>
                {
                    b.Property<int>("DispenserNozzleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("DispenserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("LastTotalCash")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastTotalLiter")
                        .HasColumnType("TEXT");

                    b.Property<int>("NozzleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DispenserNozzleId");

                    b.HasIndex("DispenserId");

                    b.HasIndex("ProductId");

                    b.ToTable("DispenserNozzle");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.PriceUpdateBatch", b =>
                {
                    b.Property<int>("PriceUpdateBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BatchExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDispensor")
                        .HasColumnType("INTEGER");

                    b.HasKey("PriceUpdateBatchId");

                    b.ToTable("PriceUpdateBatch");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.PriceUpdateLog", b =>
                {
                    b.Property<int>("PriceUpdateLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiRequest")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiResponse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("DispensorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsErrorOccured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecallAndResolve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceUpdateBatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PriceUpdateLogId");

                    b.ToTable("PriceUpdateLog");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("ProductColorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.SiteDetail", b =>
                {
                    b.Property<int>("SiteDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("SiteAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteLogo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SitePhone")
                        .HasColumnType("TEXT");

                    b.HasKey("SiteDetailId");

                    b.ToTable("SiteDetail");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("DispenserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Liter")
                        .HasColumnType("TEXT");

                    b.Property<int>("NozzleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.DispenserNozzle", b =>
                {
                    b.HasOne("Shared.FPMS_DB.Entities.Dispenser", "Dispenser")
                        .WithMany("Nozzles")
                        .HasForeignKey("DispenserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.FPMS_DB.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Dispenser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shared.FPMS_DB.Entities.Dispenser", b =>
                {
                    b.Navigation("Nozzles");
                });
#pragma warning restore 612, 618
        }
    }
}
